# © Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0


{{ if eq .Values.global.objectStorage.createCosSecret true }}
kind: Secret
apiVersion: v1
metadata:
  name: studio-cos-secret
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-40"
data:
  access-key: {{ .Values.global.objectStorage.access_key | b64enc }}
  secret-key: {{ .Values.global.objectStorage.secret_key | b64enc }}
type: ibm/ibmc-s3fs
{{ end }}
---
{{ if eq .Values.global.imagePullSecret.create true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.imagePullSecret.name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-50"
data:
  .dockerconfigjson: {{ .Values.global.imagePullSecret.b64secret }}
type: kubernetes.io/dockerconfigjson 
{{ end }}