---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cos-s3-csi-sc
provisioner: cos.s3.csi.ibm.io
parameters:
  mounter: "s3fs"
  client: "awss3"
  cosEndpoint: "http://minio.default.svc.cluster.local:9000"
  locationConstraint: "us-east-1"
  csi.storage.k8s.io/provisioner-secret-name: ${pvc.annotations['cos.csi.driver/secret']}
  csi.storage.k8s.io/provisioner-secret-namespace: ${pvc.namespace}
  csi.storage.k8s.io/node-publish-secret-name: ${pvc.annotations['cos.csi.driver/secret']}
  csi.storage.k8s.io/node-publish-secret-namespace: ${pvc.namespace}
