{{- if .Values.global.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.global.appNames.ui }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.appNames.ui }}
  annotations:
    haproxy-ingress.github.io/ssl-redirect: "true"
    haproxy-ingress.github.io/hsts: "true"
    haproxy-ingress.github.io/hsts-max-age: "31536000"
    haproxy.org/server-ssl: "true"
spec:
  {{- if .Values.global.ingress.tlsEnabled }}
  tls:
    - hosts:
        - {{ printf "%s.%s" .Values.global.appNames.ui .Values.global.ingress.host }}
      secretName: {{ .Values.global.appNames.ui }}-ingress-tls
  {{- end }}
  ingressClassName: {{ .Values.global.ingress.className }}
  rules:
    - host: {{ printf "%s.%s" .Values.global.appNames.ui .Values.global.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.global.appNames.ui }}
                port:
                  number: {{ .Values.global.oauth.oauthProxyPort }}
{{- end }}