{{- if .Values.global.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.global.appNames.ui }}
  namespace: {{ .Values.global.namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ printf "%s.%s" .Values.global.appNames.ui .Values.global.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ .Values.global.appNames.ui }}
          port: {{ .Values.global.oauth.oauthProxyPort }}
          {{- if .Values.global.ingress.tlsEnabled }}
          scheme: https
          serversTransport: self-signed-transport
          {{- end }}
  tls:
    secretName: {{ .Values.global.appNames.ui }}-ingress-tls
{{- end }}