# © Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0


---
apiVersion: v1
kind: Secret
type: cos-s3-csi-driver
metadata:
  name: populate-buckets-cos-s3fs-secret
  namespace: ${OC_PROJECT}
stringData:
  uid: "10001" # Provide uid to run as non root user. This must match runAsUser in SecurityContext of pod spec.
  bucketName: ${BUCKET_INFERENCE_AUXDATA}
  cosEndpoint: ${endpoint}
  accessKey: ${access_key_id}
  secretKey: ${secret_access_key}
  mountOptions: |
    dbglevel=info
    ssl_verify_hostname=0
    no_check_certificate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: populate-buckets-pvc
  namespace: ${OC_PROJECT}
  annotations:
    cos.csi.driver/secret: "populate-buckets-cos-s3fs-secret"
    cos.csi.driver/secret-namespace: ${OC_PROJECT}
spec:
  storageClassName: cos-s3-csi-s3fs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
