# © Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0


---
apiVersion: batch/v1
kind: Job
metadata:
  name: populate-buckets-job
  namespace: ${OC_PROJECT}
  labels:
    app: populate-buckets
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 0
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      name: populate-buckets-pod
    spec:
      restartPolicy: Never
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: populate-buckets-pvc
        - name: populate-buckets-script
          configMap:
            name: populate-buckets-script
            defaultMode: 0755
      containers:
        - name: populate-buckets
          image: registry.access.redhat.com/ubi9/ubi-minimal:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: persistent-storage
              mountPath: /data
            - name: populate-buckets-script
              mountPath: /populate-buckets-script
          command: ["/bin/sh"]
          args: ["-c", "/populate-buckets-script/populate-buckets-script.sh"]

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: populate-buckets-script
  namespace: ${OC_PROJECT}
data:
  populate-buckets-script.sh: |
    #!/bin/bash
    set -e

    # install unzip
    microdnf update -y && \
    microdnf install -y unzip && \
    microdnf clean all && \
    rm -rf /var/cache/microdnf /tmp/*

    # Function to handle errors
    error_handler() {
        local status=$?

        echo "An error occurred. Sending error notification..."
        exit $status
    }

    # Function to send success notification
    success_handler() {
        echo "Job completed successfully. Sending success notification..."
    }

    # Trap errors to call error_handler
    trap 'error_handler' ERR

    echo "Job Start..."

    cd /data

    if [ "$LULC_TILE_ROOT" ]; then
      echo "Tile root set as: $LULC_TILE_ROOT"
      mkdir -p lulc
      echo "Starting download phase"
      curl -L -# -o lulc.zip "$LULC_TILE_ROOT"
      echo "Exiting download phase"
      unzip -oj lulc.zip -d lulc
      rm lulc.zip
    fi

    if [ "$LULC_TILE_SHAPEFILE" ]; then
      echo "Lulc tile shapefile: $LULC_TILE_SHAPEFILE"
    fi

    if [ "$LAND_POLYGON_PATH" ]; then
      echo "Land polygon path set to: $LAND_POLYGON_PATH"
      mkdir -p general
      echo "Starting download phase"
      curl -L -# -o general.zip "$LAND_POLYGON_PATH"
      echo "Exiting download phase"
      unzip -oj general.zip -d general
      rm general.zip
    fi

    # Call success handler if no errors occurred
    success_handler
    echo "Job Completed..."
