#!/bin/bash

# © Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0




source workspace/$DEPLOYMENT_ENV/env/env.sh

charts=( 
        geospatial-studio
        geospatial-studio-pipelines
	)

for HELM_CHART_NAME in "${charts[@]}"
do
    echo " "
    echo "Generating values file for $HELM_CHART_NAME"

    mkdir -p workspace/$DEPLOYMENT_ENV/values/${HELM_CHART_NAME}

    sed -e "s|OC_PROJECT|${OC_PROJECT}|" \
        -e "s|CLUSTER_URL|${CLUSTER_URL}|" \
        -e "s|ENVIRONMENT_VALUE|${ENVIRONMENT}|" \
        -e "s|ROUTE_ENABLED|${ROUTE_ENABLED}|" \
        -e "s|OBSERVABILITY_ENABLED|${OBSERVABILITY_ENABLED}|" \
        -e "s|OBSERVABILITY_OTLP_ENDPOINT|${OBSERVABILITY_OTLP_ENDPOINT}|" \
        -e "s|OBSERVABILITY_OTLP_TRACES_ENDPOINT|${OBSERVABILITY_OTLP_TRACES_ENDPOINT}|" \
        -e "s|BUCKET_FINE_TUNING_MODELS|${BUCKET_FINE_TUNING_MODELS}|" \
        -e "s|BUCKET_INFERENCE_AUXDATA|${BUCKET_INFERENCE_AUXDATA}|" \
        -e "s|NON_COS_STORAGE_CLASS|${NON_COS_STORAGE_CLASS}|" \
        -e "s|BUCKET_TEMP_UPLOAD|${BUCKET_TEMP_UPLOAD}|" \
        -e "s|BUCKET_INFERENCE|${BUCKET_INFERENCE}|" \
        -e "s|BUCKET_FINE_TUNING|${BUCKET_FINE_TUNING}|" \
        -e "s|BUCKET_DATASET_FACTORY|${BUCKET_DATASET_FACTORY}|" \
        -e "s|BUCKET_AMO_INPUT_BUCKET|${BUCKET_AMO_INPUT_BUCKET}|" \
        -e "s|BUCKET_GFM_MLFLOW|${BUCKET_GFM_MLFLOW}|" \
        -e "s|BUCKET_GEOSERVER|${BUCKET_GEOSERVER}|" \
        -e "s|COS_STORAGE_CLASS|${COS_STORAGE_CLASS}|" \
        -e "s|STORAGE_PVC_ENABLED|${STORAGE_PVC_ENABLED}|" \
        -e "s|SHARE_PIPELINE_PVC|${SHARE_PIPELINE_PVC}|" \
        -e "s|STORAGE_FILESYSTEM_ENABLED|${STORAGE_FILESYSTEM_ENABLED}|" \
        -e "s|CREATE_TUNING_FOLDERS_FLAG|${CREATE_TUNING_FOLDERS_FLAG}|" \
        -e "s|OAUTH_TYPE|${OAUTH_TYPE}|" \
        -e "s|OAUTH_PROXY_ENABLED|${OAUTH_PROXY_ENABLED}|" \
        -e "s|OAUTH_PROXY_PORT|${OAUTH_PROXY_PORT}|" \
        -e "s|OAUTH_CLIENT_ID|${OAUTH_CLIENT_ID}|" \
        -e "s|OAUTH_ISSUER_URL|${OAUTH_ISSUER_URL}|" \
        -e "s|OAUTH_URL|${OAUTH_URL}|" \
        -e "s|OAUTH_EXTRA_PROXY_ARGS|${OAUTH_EXTRA_PROXY_ARGS}|" \
        -e "s|CREATE_TLS_SECRET|${CREATE_TLS_SECRET}|" \
        -e "s|REDIS_ENABLED|${REDIS_ENABLED}|" \
        -e "s|REDIS_FULL_NAME_OVERRIDE|${REDIS_FULL_NAME_OVERRIDE}|" \
        -e "s|REDIS_ARCHITECTURE|${REDIS_ARCHITECTURE}|" \
        -e "s|CONFIGURE_GPU_AFFINITY_FLAG|${CONFIGURE_GPU_AFFINITY_FLAG}|" \
        -e "s|NODE_SELECTOR_KEY|${NODE_SELECTOR_KEY}|" \
        -e "s|NODE_GPU_SPEC|${NODE_GPU_SPEC}|" \
        -e "s|GEOSERVER_CM_WHITELIST|${GEOSERVER_CM_WHITELIST}|" \
        -e "s|GEOSERVER_CM_PROXYBASEURL|${GEOSERVER_CM_PROXYBASEURL}|" \
        -e "s|geospatial-studio|${CONTAINER_IMAGE_REPOSITORY}|" \
        -e "s|PIPELINES_V2_INFERENCE_ROOT_FOLDER_VALUE|${PIPELINES_V2_INFERENCE_ROOT_FOLDER_VALUE}|" \
        -e "s|PIPELINES_TERRATORCH_INFERENCE_CREATE_FT_PVC|${PIPELINES_TERRATORCH_INFERENCE_CREATE_FT_PVC}|" \
        ${HELM_CHART_NAME}/values.yaml > workspace/$DEPLOYMENT_ENV/values/${HELM_CHART_NAME}/values.yaml
done
