#!/bin/bash

# © Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0




source workspace/$DEPLOYMENT_ENV/env/env.sh

charts=( 
        geospatial-studio
	)

for HELM_CHART_NAME in "${charts[@]}"
do
    echo " "
    echo "Generating values file for $HELM_CHART_NAME"

    mkdir -p workspace/$DEPLOYMENT_ENV/values/${HELM_CHART_NAME}

    sed -e "s|OC_PROJECT|${OC_PROJECT}|" \
        -e "s|CLUSTER_URL|${CLUSTER_URL}|" \
        -e "s|ENVIRONMENT_VALUE|${ENVIRONMENT}|" \
        -e "s|ROUTE_ENABLED|${ROUTE_ENABLED}|" \
        -e "s|OBSERVABILITY_ENABLED|${OBSERVABILITY_ENABLED}|" \
        -e "s|OBSERVABILITY_OTLP_ENDPOINT|${OBSERVABILITY_OTLP_ENDPOINT}|" \
        -e "s|OBSERVABILITY_OTLP_TRACES_ENDPOINT|${OBSERVABILITY_OTLP_TRACES_ENDPOINT}|" \
        -e "s|BUCKET_FINE_TUNING_MODELS|${BUCKET_FINE_TUNING_MODELS}|" \
        -e "s|BUCKET_INFERENCE_AUXDATA|${BUCKET_INFERENCE_AUXDATA}|" \
        -e "s|STORAGE_MODE|${STORAGE_MODE}|" \
        -e "s|NON_COS_STORAGE_CLASS|${NON_COS_STORAGE_CLASS}|" \
        -e "s|PVC_ACCESS_MODE|${PVC_ACCESS_MODE}|" \
        -e "s|BUCKET_TEMP_UPLOAD|${BUCKET_TEMP_UPLOAD}|" \
        -e "s|BUCKET_INFERENCE|${BUCKET_INFERENCE}|" \
        -e "s|BUCKET_FINE_TUNING|${BUCKET_FINE_TUNING}|" \
        -e "s|BUCKET_DATASET_FACTORY|${BUCKET_DATASET_FACTORY}|" \
        -e "s|BUCKET_AMO_INPUT_BUCKET|${BUCKET_AMO_INPUT_BUCKET}|" \
        -e "s|BUCKET_GFM_MLFLOW|${BUCKET_GFM_MLFLOW}|" \
        -e "s|BUCKET_GEOSERVER|${BUCKET_GEOSERVER}|" \
        -e "s|BUCKET_GENERIC_PYTHON_PROCESSOR|${BUCKET_GENERIC_PYTHON_PROCESSOR}|" \
        -e "s|BUCKET_PIPELINE_DATA|${BUCKET_PIPELINE_DATA}|" \
        -e "s|COS_STORAGE_CLASS|${COS_STORAGE_CLASS}|" \
        -e "s|SHARE_PIPELINE_PVC|${SHARE_PIPELINE_PVC}|" \
        -e "s|OAUTH_TYPE|${OAUTH_TYPE}|" \
        -e "s|OAUTH_PROXY_PORT|${OAUTH_PROXY_PORT}|" \
        -e "s|OAUTH_CLIENT_ID|${OAUTH_CLIENT_ID}|" \
        -e "s|OAUTH_ISSUER_URL|${OAUTH_ISSUER_URL}|" \
        -e "s|OAUTH_URL|${OAUTH_URL}|" \
        -e "s|OAUTH_EXTRA_PROXY_ARGS|${OAUTH_EXTRA_PROXY_ARGS}|" \
        -e "s|CREATE_TLS_SECRET|${CREATE_TLS_SECRET}|" \
        -e "s|PGBOUNCER_ENABLED|${PGBOUNCER_ENABLED}|" \
        -e "s|PGBOUNCER_FULL_NAME_OVERRIDE|${PGBOUNCER_FULL_NAME_OVERRIDE}|" \
        -e "s|REDIS_ENABLED|${REDIS_ENABLED}|" \
        -e "s|REDIS_FULL_NAME_OVERRIDE|${REDIS_FULL_NAME_OVERRIDE}|" \
        -e "s|REDIS_ARCHITECTURE|${REDIS_ARCHITECTURE}|" \
        -e "s|PIPELINES_ENABLED|${PIPELINES_ENABLED}|" \
        -e "s|CONFIGURE_GPU_AFFINITY_FLAG|${CONFIGURE_GPU_AFFINITY_FLAG}|" \
        -e "s|CONFIGURE_GPU_AFFINITY|${CONFIGURE_GPU_AFFINITY}|" \
        -e "s|NODE_SELECTOR_KEY|${NODE_SELECTOR_KEY}|" \
        -e "s|NODE_GPU_SPEC|${NODE_GPU_SPEC}|" \
        -e "s|GEOSERVER_CM_WHITELIST|${GEOSERVER_CM_WHITELIST}|" \
        -e "s|GEOSERVER_CM_PROXYBASEURL|${GEOSERVER_CM_PROXYBASEURL}|" \
        -e "s|geospatial-studio|${CONTAINER_IMAGE_REPOSITORY}|" \
        -e "s|PIPELINES_V2_INFERENCE_ROOT_FOLDER_VALUE|${PIPELINES_V2_INFERENCE_ROOT_FOLDER_VALUE}|" \
        -e "s|TERRAKIT_CACHE_ENABLED_VALUE|${TERRAKIT_CACHE_ENABLED_VALUE}|" \
        -e "s|TERRAKIT_CACHE_DIR_VALUE|${TERRAKIT_CACHE_DIR_VALUE}|" \
        ${HELM_CHART_NAME}/values.yaml > workspace/$DEPLOYMENT_ENV/values/${HELM_CHART_NAME}/values.yaml
done
