{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullnameOverride }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.fullnameOverride }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.fullnameOverride }}
  template:
    metadata:
      labels:
        app: {{ .Values.fullnameOverride }}
    spec:
      {{- if .Values.podSecurityContext.enabled }}
      securityContext:
        runAsUser: {{ .Values.podSecurityContext.runAsUser }}
      {{- end }}
      containers:
      - name: pgbouncer
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        {{- if .Values.image.pullPolicy }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- end }}
        {{- if .Values.containerSecurityContext.enabled }}
        securityContext:
          runAsUser: {{ .Values.containerSecurityContext.runAsUser }}
        {{- end }}
        ports:
        - name: pgbouncer
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ .Values.fullnameOverride }}-config
        env:
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.fullnameOverride }}-secret
              key: postgresql-password
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          tcpSocket:
            port: pgbouncer
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: pgbouncer
          initialDelaySeconds: 5
          periodSeconds: 5
{{- end }}
