# © Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0
#
# DaemonSet to pre-pull container images
# Automatically configured for single-node or multi-node clusters
#
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: geostudio-image-prepuller
  namespace: OC_PROJECT
  labels:
    app: geostudio-image-prepuller
    component: image-prepuller
spec:
  selector:
    matchLabels:
      name: geostudio-image-prepuller
  template:
    metadata:
      labels:
        name: geostudio-image-prepuller
        app: geostudio-image-prepuller
    spec:
      # NODE_AFFINITY_PLACEHOLDER
      
      # Allow scheduling on tainted nodes
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      
      # Pull images sequentially in init containers
      initContainers:
      
      # 1. OAuth Proxy (~100MB)
      - name: prepull-01-oauth-proxy
        image: bitnamilegacy/oauth2-proxy:latest
        command: ['sh', '-c', 'echo "✓ OAuth proxy image pulled" && sleep 1']
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
      
      # 2. Gateway (~500MB-1GB)
      - name: prepull-02-gateway
        image: quay.io/geospatial-studio/geostudio-gateway:latest
        command: ['sh', '-c', 'echo "✓ Gateway image pulled" && sleep 1']
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 200Mi
      
      # 3. Kubectl (~50MB)
      - name: prepull-03-kubectl
        image: bitnamilegacy/kubectl:latest
        command: ['sh', '-c', 'echo "✓ Kubectl image pulled" && sleep 1']
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
      
      # 4. Pipelines (~500MB-1GB)
      - name: prepull-04-pipelines
        image: quay.io/geospatial-studio/geostudio-pipelines:latest
        command: ['sh', '-c', 'echo "✓ Pipelines image pulled" && sleep 1']
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 200Mi
      
      # 5. YQ (~20MB)
      - name: prepull-05-yq
        image: linuxserver/yq:latest
        command: ['sh', '-c', 'echo "✓ YQ image pulled" && sleep 1']
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
      
      # 6. UI (~200-500MB)
      - name: prepull-06-ui
        image: quay.io/geospatial-studio/geostudio-ui:latest
        command: ['sh', '-c', 'echo "✓ UI image pulled" && sleep 1']
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 200Mi
      
      # 7. MLflow (~500MB-1GB)
      - name: prepull-07-mlflow
        image: ghcr.io/mlflow/mlflow:latest
        command: ['sh', '-c', 'echo "✓ MLflow image pulled" && sleep 1']
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 200Mi
      
      # 8. Redis (~100MB)
      - name: prepull-08-redis
        image: bitnamilegacy/redis:latest
        command: ['sh', '-c', 'echo "✓ Redis image pulled" && sleep 1']
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
      
      # 9. Terratorch (~3-5GB - Largest, GPU-focused)
      - name: prepull-09-terratorch
        image: quay.io/geospatial-studio/terratorch:latest
        command: ['sh', '-c', 'echo "✓ Terratorch image pulled" && sleep 1']
        resources:
          requests:
            cpu: 10m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 500Mi
      
      # 10. MinIO (~100MB)
      - name: prepull-10-minio
        image: quay.io/minio/minio:latest
        command: ['sh', '-c', 'echo "✓ MinIO image pulled" && sleep 1']
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
      
      # 11. PostgreSQL (~200MB)
      - name: prepull-11-postgresql
        image: bitnamilegacy/postgresql:latest
        command: ['sh', '-c', 'echo "✓ PostgreSQL image pulled" && sleep 1']
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 200Mi
      
      # 12. OS Shell (~50MB)
      - name: prepull-12-os-shell
        image: bitnamilegacy/os-shell:latest
        command: ['sh', '-c', 'echo "✓ OS Shell image pulled" && sleep 1']
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
      
      # 13. Keycloak (~500MB)
      - name: prepull-13-keycloak
        image: quay.io/keycloak/keycloak:26.4.5
        command: ['sh', '-c', 'echo "✓ Keycloak image pulled" && sleep 1']
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 200Mi
      
      # 14. GeoServer (~500MB-1GB)
      - name: prepull-14-geoserver
        image: docker.osgeo.org/geoserver:2.28.1
        command: ['sh', '-c', 'echo "✓ GeoServer image pulled" && sleep 1']
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 200Mi
      
      # Main container - keeps pod running for monitoring
      containers:
      - name: monitor
        image: busybox:latest
        command: ['sh', '-c', 'echo "All images pulled successfully. Pod will remain running for monitoring." && sleep infinity']
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 50m
            memory: 50Mi
      
      # Use image pull secret if required
      imagePullSecrets:
      - name: us-icr-pull-secret
      
      restartPolicy: Always
