{{- if .Values.global.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.global.appNames.mlflow }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.appNames.mlflow }}
  annotations:
    haproxy-ingress.github.io/ssl-redirect: "true"
    haproxy-ingress.github.io/hsts: "true"
    haproxy-ingress.github.io/hsts-max-age: "31536000"
spec:
  ingressClassName: {{ .Values.global.ingress.className }}
  rules:
    - host: {{ printf "%s.%s" .Values.global.appNames.mlflow .Values.global.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.global.appNames.mlflow }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}