# © Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0


apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.appNames.mlflow }}-secrets
type: Opaque
data:
  BACKEND_URI: {{ include "geospatial-studio.postgres.mlflow.backend.uri" . | b64enc }}
