# © Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0


apiVersion: v1
kind: Secret
metadata:
  name: pipelines-orchestration-db  # Name of your secret
  namespace: {{ .Values.namespace }}   # Namespace where the secret will be created
type: Opaque
data:
  orchestrate_db_uri: {{ printf "postgresql+pg8000://%s:%s@%s:%d/%s"  .Values.orchestrate_db.pg_username .Values.orchestrate_db.pg_password .Values.orchestrate_db.pg_uri (.Values.orchestrate_db.pg_port | int) .Values.orchestrate_db.pg_studio_db_name | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pipeline-gateway-creds  # Name of your secret
  namespace: {{ .Values.namespace }}   # Namespace where the secret will be created
type: Opaque
data:
  gfmaas_api_key: {{ .Values.gateway.api_key | b64enc }}
  geoserver_username: {{ .Values.geoserver.username | b64enc }}
  geoserver_password: {{ .Values.geoserver.password | b64enc }}

---
{{ if hasKey .Values "nasaEarthBearerToken"}}
apiVersion: v1
kind: Secret
metadata:
  name: nasa-earth-data-secret  # Name of your secret
  namespace: {{ .Values.namespace }}   # Namespace where the secret will be created
type: Opaque
data:
  NASA_EARTH_BEARER_TOKEN: {{ .Values.nasaEarthBearerToken | default "" | b64enc | quote }}
{{ end }}
---
{{ if hasKey .Values "sentinelhub"}}
apiVersion: v1
kind: Secret
metadata:
  name: sentinelhub-creds  # Name of your secret
  namespace: {{ .Values.namespace }}   # Namespace where the secret will be created
type: Opaque
data:
  SH_CLIENT_ID: {{ .Values.sentinelhub.client_id | default "" | b64enc | quote }}
  SH_CLIENT_SECRET: {{ .Values.sentinelhub.client_secret | default "" | b64enc | quote }}
{{ end }}
---
{{ if eq .Values.imagePullSecret.create true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: {{ .Values.imagePullSecret.b64secret }}
type: kubernetes.io/dockerconfigjson 
{{ end }}
---
{{ if eq .Values.objectStorage.createCosSecret true }}
kind: Secret
apiVersion: v1
metadata:
  name: studio-cos-secret
  namespace: {{ .Values.namespace }}
data:
  access-key: {{ .Values.objectStorage.access_key | b64enc }}
  secret-key: {{ .Values.objectStorage.secret_key | b64enc }}
type: ibm/ibmc-s3fs
{{ end }}
